package com.flowsoft.wanda;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.7.0 2012-11-12T16:18:39.907+01:00
 * Generated source version: 2.7.0
 * 
 */
public final class UserDetailsService_UserDetailsServiceImplPort_Client {

	private static final QName SERVICE_NAME = new QName(
			"http://wanda.flowsoft.com/", "UserDetailsServiceImplService");

	private UserDetailsService_UserDetailsServiceImplPort_Client() {
	}

	public static void main(String args[]) throws java.lang.Exception {
		URL wsdlURL = UserDetailsServiceImplService.WSDL_LOCATION;
		if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}

		UserDetailsServiceImplService ss = new UserDetailsServiceImplService(
				wsdlURL, SERVICE_NAME);
		UserDetailsService port = ss.getUserDetailsServiceImplPort();

		{
			System.out.println("Invoking initTestDb...");
			port.initTestDb();

		}
		{
			System.out.println("Invoking findByUsername...");
			java.lang.String _findByUsername_arg0 = "_findByUsername_arg01484793706";
			com.flowsoft.wanda.WandaUser _findByUsername__return = port
					.findByUsername(_findByUsername_arg0);
			System.out.println("findByUsername.result="
					+ _findByUsername__return);

		}
		{
			System.out.println("Invoking getArticleContentByTitle...");
			java.lang.String _getArticleContentByTitle_arg0 = "_getArticleContentByTitle_arg0216871347";
			java.lang.String _getArticleContentByTitle__return = port
					.getArticleContentByTitle(_getArticleContentByTitle_arg0);
			System.out.println("getArticleContentByTitle.result="
					+ _getArticleContentByTitle__return);

		}
		{
			System.out.println("Invoking createArticle...");
			com.flowsoft.wanda.WandaUser _createArticle_arg0 = new com.flowsoft.wanda.WandaUser();
			_createArticle_arg0.setCreatedTS(javax.xml.datatype.DatatypeFactory
					.newInstance().newXMLGregorianCalendar(
							"2012-11-12T16:18:40.042+01:00"));
			_createArticle_arg0.setEmailAdress("EmailAdress667969427");
			_createArticle_arg0.setEnabled(Boolean.valueOf(false));
			_createArticle_arg0.setFirstName("FirstName-2121039102");
			_createArticle_arg0.setLastName("LastName-1866306264");
			_createArticle_arg0
					.setModifiedTS(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2012-11-12T16:18:40.065+01:00"));
			_createArticle_arg0.setPassword("Password207002335");
			_createArticle_arg0.setRole("Role1135428912");
			_createArticle_arg0.setUsername("Username-1238662926");
			java.lang.String _createArticle_arg1 = "_createArticle_arg1-377042078";
			java.lang.String _createArticle_arg2 = "_createArticle_arg2-1026145983";
			port.createArticle(_createArticle_arg0, _createArticle_arg1,
					_createArticle_arg2);

		}
		{
			System.out.println("Invoking findAllArticle...");
			java.lang.String _findAllArticle_arg0 = "_findAllArticle_arg0-244516359";
			java.util.List<com.flowsoft.wanda.Article> _findAllArticle__return = port
					.findAllArticle(_findAllArticle_arg0);
			System.out.println("findAllArticle.result="
					+ _findAllArticle__return);

		}
		{
			System.out.println("Invoking findArticleByTitle...");
			java.lang.String _findArticleByTitle_arg0 = "_findArticleByTitle_arg0765903150";
			com.flowsoft.wanda.Article _findArticleByTitle__return = port
					.findArticleByTitle(_findArticleByTitle_arg0);
			System.out.println("findArticleByTitle.result="
					+ _findArticleByTitle__return);

		}
		{
			System.out.println("Invoking editArticle...");
			java.lang.String _editArticle_arg0 = "_editArticle_arg01991423107";
			java.lang.String _editArticle_arg1 = "_editArticle_arg1144576724";
			port.editArticle(_editArticle_arg0, _editArticle_arg1);

		}
		{
			System.out.println("Invoking createUser...");
			java.lang.String _createUser_arg0 = "_createUser_arg01262307982";
			java.lang.String _createUser_arg1 = "_createUser_arg1309759157";
			java.lang.String _createUser_arg2 = "_createUser_arg2-191506145";
			java.lang.String _createUser_arg3 = "_createUser_arg3-323587841";
			java.lang.Boolean _createUser__return = port.createUser(
					_createUser_arg0, _createUser_arg1, _createUser_arg2,
					_createUser_arg3);
			System.out.println("createUser.result=" + _createUser__return);

		}
		{
			System.out.println("Invoking exist...");
			java.lang.String _exist_arg0 = "_exist_arg0450160280";
			java.lang.Boolean _exist__return = port.exist(_exist_arg0);
			System.out.println("exist.result=" + _exist__return);

		}
		{
			System.out.println("Invoking findAllUser...");
			java.util.List<com.flowsoft.wanda.WandaUser> _findAllUser__return = port
					.findAllUser();
			System.out.println("findAllUser.result=" + _findAllUser__return);

		}
		{
			System.out.println("Invoking createCategory...");
			com.flowsoft.wanda.WandaUser _createCategory_arg0 = new com.flowsoft.wanda.WandaUser();
			_createCategory_arg0
					.setCreatedTS(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2012-11-12T16:18:40.071+01:00"));
			_createCategory_arg0.setEmailAdress("EmailAdress-1168452379");
			_createCategory_arg0.setEnabled(Boolean.valueOf(true));
			_createCategory_arg0.setFirstName("FirstName133594090");
			_createCategory_arg0.setLastName("LastName1834183856");
			_createCategory_arg0
					.setModifiedTS(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2012-11-12T16:18:40.072+01:00"));
			_createCategory_arg0.setPassword("Password-1802611701");
			_createCategory_arg0.setRole("Role1314505247");
			_createCategory_arg0.setUsername("Username769860397");
			java.lang.String _createCategory_arg1 = "_createCategory_arg11261290238";
			port.createCategory(_createCategory_arg0, _createCategory_arg1);

		}
		{
			System.out.println("Invoking findAllCommentFor...");
			java.lang.String _findAllCommentFor_arg0 = "_findAllCommentFor_arg0-1069833415";
			java.util.List<com.flowsoft.wanda.Comment> _findAllCommentFor__return = port
					.findAllCommentFor(_findAllCommentFor_arg0);
			System.out.println("findAllCommentFor.result="
					+ _findAllCommentFor__return);

		}
		{
			System.out.println("Invoking deleteCategory...");
			java.lang.String _deleteCategory_arg0 = "_deleteCategory_arg01398244351";
			java.lang.String _deleteCategory_arg1 = "_deleteCategory_arg1-183538742";
			port.deleteCategory(_deleteCategory_arg0, _deleteCategory_arg1);

		}
		{
			System.out.println("Invoking deleteArticle...");
			java.lang.String _deleteArticle_arg0 = "_deleteArticle_arg0469030435";
			java.lang.String _deleteArticle_arg1 = "_deleteArticle_arg1-909289124";
			java.lang.String _deleteArticle__return = port.deleteArticle(
					_deleteArticle_arg0, _deleteArticle_arg1);
			System.out
					.println("deleteArticle.result=" + _deleteArticle__return);

		}

		System.exit(0);
	}

}
