package com.flowsoft.wanda;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2012-11-12T16:18:40.104+01:00
 * Generated source version: 2.7.0
 * 
 */
@WebServiceClient(name = "UserDetailsServiceImplService", 
                  wsdlLocation = "http://localhost:8081/WandaWebapp/userDetailsService?wsdl",
                  targetNamespace = "http://wanda.flowsoft.com/") 
public class UserDetailsServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://wanda.flowsoft.com/", "UserDetailsServiceImplService");
    public final static QName UserDetailsServiceImplPort = new QName("http://wanda.flowsoft.com/", "UserDetailsServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8081/WandaWebapp/userDetailsService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UserDetailsServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8081/WandaWebapp/userDetailsService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UserDetailsServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UserDetailsServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserDetailsServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UserDetailsServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UserDetailsServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UserDetailsServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns UserDetailsService
     */
    @WebEndpoint(name = "UserDetailsServiceImplPort")
    public UserDetailsService getUserDetailsServiceImplPort() {
        return super.getPort(UserDetailsServiceImplPort, UserDetailsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserDetailsService
     */
    @WebEndpoint(name = "UserDetailsServiceImplPort")
    public UserDetailsService getUserDetailsServiceImplPort(WebServiceFeature... features) {
        return super.getPort(UserDetailsServiceImplPort, UserDetailsService.class, features);
    }

}
