package com.flowsoft.wanda;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2012-11-12T16:18:40.076+01:00
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://wanda.flowsoft.com/", name = "UserDetailsService")
@XmlSeeAlso({ObjectFactory.class})
public interface UserDetailsService {

    @RequestWrapper(localName = "initTestDb", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.InitTestDb")
    @WebMethod
    @ResponseWrapper(localName = "initTestDbResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.InitTestDbResponse")
    public void initTestDb();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findByUsername", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.FindByUsername")
    @WebMethod
    @ResponseWrapper(localName = "findByUsernameResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.FindByUsernameResponse")
    public com.flowsoft.wanda.WandaUser findByUsername(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getArticleContentByTitle", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.GetArticleContentByTitle")
    @WebMethod
    @ResponseWrapper(localName = "getArticleContentByTitleResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.GetArticleContentByTitleResponse")
    public java.lang.String getArticleContentByTitle(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @RequestWrapper(localName = "createArticle", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.CreateArticle")
    @WebMethod
    @ResponseWrapper(localName = "createArticleResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.CreateArticleResponse")
    public void createArticle(
        @WebParam(name = "arg0", targetNamespace = "")
        com.flowsoft.wanda.WandaUser arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllArticle", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.FindAllArticle")
    @WebMethod
    @ResponseWrapper(localName = "findAllArticleResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.FindAllArticleResponse")
    public java.util.List<com.flowsoft.wanda.Article> findAllArticle(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findArticleByTitle", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.FindArticleByTitle")
    @WebMethod
    @ResponseWrapper(localName = "findArticleByTitleResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.FindArticleByTitleResponse")
    public com.flowsoft.wanda.Article findArticleByTitle(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @RequestWrapper(localName = "editArticle", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.EditArticle")
    @WebMethod
    @ResponseWrapper(localName = "editArticleResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.EditArticleResponse")
    public void editArticle(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createUser", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.CreateUser")
    @WebMethod
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.CreateUserResponse")
    public java.lang.Boolean createUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "exist", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.Exist")
    @WebMethod
    @ResponseWrapper(localName = "existResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.ExistResponse")
    public java.lang.Boolean exist(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllUser", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.FindAllUser")
    @WebMethod
    @ResponseWrapper(localName = "findAllUserResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.FindAllUserResponse")
    public java.util.List<com.flowsoft.wanda.WandaUser> findAllUser();

    @RequestWrapper(localName = "createCategory", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.CreateCategory")
    @WebMethod
    @ResponseWrapper(localName = "createCategoryResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.CreateCategoryResponse")
    public void createCategory(
        @WebParam(name = "arg0", targetNamespace = "")
        com.flowsoft.wanda.WandaUser arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllCommentFor", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.FindAllCommentFor")
    @WebMethod
    @ResponseWrapper(localName = "findAllCommentForResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.FindAllCommentForResponse")
    public java.util.List<com.flowsoft.wanda.Comment> findAllCommentFor(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @RequestWrapper(localName = "deleteCategory", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.DeleteCategory")
    @WebMethod
    @ResponseWrapper(localName = "deleteCategoryResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.DeleteCategoryResponse")
    public void deleteCategory(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteArticle", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.DeleteArticle")
    @WebMethod
    @ResponseWrapper(localName = "deleteArticleResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.DeleteArticleResponse")
    public java.lang.String deleteArticle(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
